defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

commands: 
  install_npm_packages:
    steps:
      - run: npm i

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - install_npm_packages
      - save_cache:
          key: npm-packages
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: npm-packages
      - install_npm_packages
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: npm-packages
      - install_npm_packages
      - run: npm audit

workflows:
  ci-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
